language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements-test.txt
  - pip install -r requirements-cli.txt
  - pip install -r requirements-build.txt
  - pip install coveralls
script:
  - coverage run --source conbench -m pytest conbench/tests/
services:
  - postgresql
before_script:
  - psql -c 'create database conbench_test;' -U postgres
after_success:
  - coveralls
